[tool.poetry]
name = "pandandic"
version = "0.2.3"
description = "A typed dataframe helper"
license = "MIT"
authors = ["Will Martin <will.st4@gmail.com>"]
readme = "README.md"
repository = "https://github.com/w-martin/pandandic"
packages = [{ include = "pandandic", from = "src" }]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.2"
typing_extensions = { version = "^4", python = "<3.11" }
pyarrow = { version = ">=14.0.1", optional = true }  # https://github.com/advisories/GHSA-5wvp-7f3h-6wmm
pandavro = { version = "^1.7.1", optional = true }

[tool.poetry.extras]
avro = ["pandavro"]
parquet = ["pyarrow"]
extras = ["pandavro", "pyarrow"]
all = ["pandavro", "pyarrow"]

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
nose2 = "^0.12"
xlsxwriter = "^3.0.3"
openpyxl = "^3.0.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
