version: 0.2

env:
  secrets-manager:
    POETRY_PYPI_TOKEN_PYPI: "pandandic/pypi:POETRY_PYPI_TOKEN_PYPI"

phases:
  install:
    commands:
      - pip3 install awscli pip --upgrade --user
      - curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.2.2 python3 -
      - export PATH=/root/.local/bin:$PATH
  build:
    commands:
      - poetry publish --build